### ISSUE TITLE
Have an easy way to find a SO question in StackTracker

### ISSUE THREAD

**Issue by andrewkreid** [roboticdog/mernessa#24]
If I'm browsing StackOverflow and find a question I want to track in StackTracker, there should be some easy way to go straight to it.

Possibly:

1. Search by SO message ID.
2. Type entire SO question URL into StackTracker search bar and have it find the question.
3. An "Open in StackTracker" Chrome extension.

**Comment by roboticdog** [comment]
As in, searching the database of questions and displaying based on a matching ID/URL, or actually retrieving specific questions based on ID/URL from StackExchange, and adding them to the database?
Like if there is a question you're interested in monitoring, but hasn't been picked up by the application automatically should you have the ability to add it manually?

**Comment by roboticdog** [comment]
I've added a search bar for URL and ID, but I'll leave this open.
Now that I think about, manually being able to add questions to the application is a definite must.

**Comment by andrewkreid** [comment]
I agree. You might find a SO question that isn't tagged appropriately and want to add it to StackTracker right away.

**Comment by roboticdog** [comment]
I'm going to close this for now, I've opened a new issue for manual entry.
